# Generated by Django 5.1.7 on 2025-03-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_restraunt_menu_remove_restraunt_offers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restraunt',
            new_name='Restaraunt',
        ),
        migrations.AlterModelTable(
            name='restaraunt',
            table='restaraunt',
        ),
    ]
