# Generated by Django 5.1.7 on 2025-03-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_restaraunt_restraunts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaraunt',
            old_name='restraunts',
            new_name='restaraunt',
        ),
    ]
