# Generated by Django 5.1.7 on 2025-03-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_restaraunt_latitude_alter_restaraunt_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='longitude',
            field=models.DecimalField(blank=True, db_column='longitude', decimal_places=20, max_digits=20, null=True),
        ),
    ]
