# Generated by Django 5.1.7 on 2025-03-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('name', models.TextField()),
                ('password', models.TextField()),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('preference', models.JSONField(blank=True, db_column='Preference', null=True)),
            ],
            options={
                'db_table': 'user_register',
                'managed': True,
            },
        ),
    ]
