# Generated by Django 5.1.7 on 2025-03-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restraunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(db_column='Location')),
                ('restraunts', models.TextField(db_column='restraunts')),
                ('menu', models.TextField(db_column='menu')),
                ('offers', models.TextField(db_column='offers', null=True)),
            ],
            options={
                'db_table': 'restraunt',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='userregister',
            options={'managed': False},
        ),
    ]
