# Generated by Django 5.1.7 on 2025-03-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_restraunt_restaraunt_alter_restaraunt_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaraunt',
            name='restraunts',
            field=models.TextField(db_column='restaraunt'),
        ),
    ]
