# Generated by Django 5.1.7 on 2025-03-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_restraunts_restaraunt_restaraunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaraunt',
            name='restaraunt',
            field=models.TextField(db_column='Restaraunt'),
        ),
    ]
