# Generated by Django 5.1.7 on 2025-03-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_restaraunt_restaraunt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregister',
            options={'managed': True},
        ),
    ]
