# Generated by Django 5.1.7 on 2025-03-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_userregister_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='preference',
            field=models.JSONField(blank=True, db_column='preference', null=True),
        ),
    ]
