# Generated by Django 5.1.7 on 2025-03-22 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_userregister_preference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaraunt',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userregister',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_text', models.IntegerField(blank=True, null=True)),
                ('rating', models.TextField(choices=[('1', '1 - Poor'), ('2', '2 - Fair'), ('3', '3 - Good'), ('4', '4 - Very Good'), ('5', '5 - Excellent')])),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restaraunt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userregister')),
            ],
            options={
                'db_table': 'reviews',
                'managed': True,
            },
        ),
    ]
