# Generated by Django 5.1.7 on 2025-03-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_restaraunt_options_alter_userregister_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaraunt',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userregister',
            options={'managed': True},
        ),
    ]
