# Generated by Django 5.1.7 on 2025-03-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_restaraunt_options_alter_reviews_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaraunt',
            name='latitude',
            field=models.DecimalField(blank=True, db_column='latitude', decimal_places=9, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='restaraunt',
            name='longitude',
            field=models.DecimalField(blank=True, db_column='longitude', decimal_places=9, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='latitude',
            field=models.DecimalField(blank=True, db_column='latitude', decimal_places=9, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='longitude',
            field=models.DecimalField(blank=True, db_column='longitude', decimal_places=9, max_digits=9, null=True),
        ),
    ]
