# Generated by Django 5.1.7 on 2025-03-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_restaraunt_latitude_restaraunt_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaraunt',
            name='latitude',
            field=models.DecimalField(blank=True, db_column='latitude', decimal_places=20, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='restaraunt',
            name='longitude',
            field=models.DecimalField(blank=True, db_column='longitude', decimal_places=20, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='latitude',
            field=models.DecimalField(blank=True, db_column='latitude', decimal_places=20, max_digits=20, null=True),
        ),
    ]
