# Generated by Django 5.1.7 on 2025-03-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_userregister_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaraunt',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userregister',
            options={'managed': False},
        ),
    ]
