# Generated by Django 5.1.7 on 2025-03-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_restaraunt_options_alter_userregister_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaraunt',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userregister',
            options={'managed': False},
        ),
    ]
