# Generated by Django 5.1.7 on 2025-03-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_restaraunt_options_alter_userregister_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaraunt',
            name='latitude',
            field=models.FloatField(blank=True, db_column='latitude', null=True),
        ),
        migrations.AlterField(
            model_name='restaraunt',
            name='longitude',
            field=models.FloatField(blank=True, db_column='longitude', null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='latitude',
            field=models.FloatField(blank=True, db_column='latitude', null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='longitude',
            field=models.FloatField(blank=True, db_column='longitude', null=True),
        ),
    ]
