# Generated by Django 5.1.7 on 2025-03-29 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_restaraunt_latitude_alter_restaraunt_longitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'managed': True},
        ),
    ]
